#!/bin/bash
# Opt-in: installs the theme-set hook that keeps the cursor color following
# the active Omarchy theme automatically. Run this yourself; nothing in this
# plugin does it on install (see README.md).
#
# omarchy-hook-install copies the hook file into
# ~/.config/omarchy/hooks/theme-set.d/, it does not symlink it, so the
# installed copy can't find its own plugin directory by relative path once
# it's been moved there. Generate the hook with this plugin's real absolute
# path baked in, rather than shipping a static file that assumes it's still
# sitting next to recolor.py.
set -euo pipefail
PLUGIN_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"

tmp=$(mktemp -d)/cursor-accent.sh
trap 'rm -rf "$(dirname "$tmp")"' EXIT
cat > "$tmp" <<EOF
#!/bin/bash
# Generated by install-cursor-hook.sh, with this plugin's actual install
# path baked in (see that script for why). Re-run it after moving the
# plugin, or after \`omarchy plugin update\` if the install path ever changes.
exec python3 "$PLUGIN_DIR/recolor.py" "\$@"
EOF

omarchy hook install theme-set "$tmp"
echo "Applying the current theme's colors now..."
"$PLUGIN_DIR/cursor-accent" follow
